version: 0.2

env:
  parameter-store:
    SECRET_TOKEN: "MY_SECRET_TOKEN"
phases:
  install:
    commands:
      - echo Installing Maven...
  build:
    commands:
      - echo Running mvn
      - mvn --$ENVVAR
