version: 0.2

env:
  parameter-store:
    DB_USERNAME: "db_username"
phases:
  install:
    commands:
      - echo Installing Maven...
  build:
    commands:
      - echo Running mvn
      - mvn --$ENVVAR
